# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import django.contrib.auth.models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFactTable',
            fields=[
                ('fact_id', models.AutoField(serialize=False, primary_key=True)),
                ('fact_city', models.CharField(max_length=45)),
                ('fact_state', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('user_ptr', models.OneToOneField(parent_link=True, auto_created=True, to=settings.AUTH_USER_MODEL)),
                ('consumer_id', models.AutoField(serialize=False, primary_key=True)),
                ('consumer_email', models.CharField(max_length=45)),
                ('consumer_contactno', models.CharField(max_length=45, null=True, blank=True)),
                ('consumer_first_name', models.CharField(max_length=45)),
                ('consumer_last_name', models.CharField(max_length=45)),
                ('sign_up_via', models.CharField(max_length=10, null=True, blank=True)),
                ('sign_up_source', models.CharField(max_length=10, null=True, blank=True)),
                ('apns_token', models.CharField(max_length=10, null=True, blank=True)),
                ('consumer_image', models.ImageField(default=None, upload_to=b'images/', max_length=255, verbose_name=b'Image')),
                ('consumer_city', models.CharField(max_length=45, null=True, blank=True)),
                ('consumer_state', models.CharField(max_length=45, null=True, blank=True)),
                ('consumer_country', models.CharField(max_length=45, null=True, blank=True)),
                ('consumer_gender', models.CharField(max_length=1, null=True, blank=True)),
                ('consumer_age', models.IntegerField(null=True, blank=True)),
                ('consumer_location', models.CharField(max_length=45, null=True, blank=True)),
                ('consumer_feedback', models.CharField(max_length=200, null=True, blank=True)),
                ('consumer_brownypoint', models.IntegerField(null=True, blank=True)),
                ('is_consumer_email_alert', models.CharField(max_length=1, null=True, blank=True)),
                ('is_consumer_sms_alert', models.CharField(max_length=1, null=True, blank=True)),
                ('consumer_create_by', models.CharField(max_length=45, null=True, blank=True)),
                ('consumer_create_date', models.DateTimeField(null=True, blank=True)),
                ('consumer_update_by', models.CharField(max_length=45, null=True, blank=True)),
                ('consumer_update_date', models.DateTimeField(null=True, blank=True)),
                ('consumer_status', models.CharField(max_length=1, null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerPaymentCredentials',
            fields=[
                ('consumer_payment_id', models.AutoField(serialize=False, primary_key=True)),
                ('consumer_payment_bankname', models.CharField(max_length=45)),
                ('consumer_payment_cardno', models.CharField(max_length=45)),
                ('consumer_payment_cardtype', models.CharField(max_length=45)),
                ('consumer_payment_cvv', models.CharField(max_length=45)),
                ('consumer_payment_expdate', models.DateField()),
                ('consumer_payment_datetime', models.DateTimeField(verbose_name=b'payment datetime')),
                ('consumer_payment_create_by', models.CharField(max_length=45)),
                ('consumer_payment_create_date', models.DateTimeField(verbose_name=b'payment create')),
                ('consumer_payment_update_date', models.DateTimeField(verbose_name=b'payment update')),
                ('consumer_payment_update_by', models.CharField(max_length=45)),
                ('consumer_payment_status', models.CharField(max_length=1)),
                ('consumer_id', models.ForeignKey(to='dealmonkapp.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='CuisineFactTable',
            fields=[
                ('fact_id', models.AutoField(serialize=False, primary_key=True)),
                ('fact_cuisine', models.CharField(max_length=70)),
                ('fact_cuisine_create_date', models.DateTimeField(null=True, blank=True)),
                ('fact_cuisine_create_by', models.CharField(default=None, max_length=45, blank=True)),
                ('fact_cuisine_update_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('fact_cuisine_update_by', models.CharField(default=None, max_length=45, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuisineRestaurentBranchMap',
            fields=[
                ('cuisine_rest_branch_id', models.AutoField(serialize=False, primary_key=True)),
                ('cuisine_rest_branch_create_date', models.DateTimeField(null=True, blank=True)),
                ('cuisine_rest_branch_create_by', models.CharField(default=None, max_length=45, blank=True)),
                ('cuisine_rest_branch_update_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('cuisine_rest_branch_update_by', models.CharField(default=None, max_length=45, blank=True)),
                ('cuisine_id', models.ForeignKey(default=None, blank=True, to='dealmonkapp.CuisineFactTable', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuisineRestaurentMap',
            fields=[
                ('cuisine_rest_id', models.AutoField(serialize=False, primary_key=True)),
                ('cuisine_rest_create_date', models.DateTimeField(null=True, blank=True)),
                ('cuisine_rest_create_by', models.CharField(default=None, max_length=45, blank=True)),
                ('cuisine_rest_update_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('cuisine_rest_update_by', models.CharField(default=None, max_length=45, blank=True)),
                ('cuisine_id', models.ForeignKey(default=None, blank=True, to='dealmonkapp.CuisineFactTable', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(serialize=False, primary_key=True)),
                ('invoice_datetime', models.DateTimeField(verbose_name=b'invoice datetime')),
                ('invoice_amount', models.IntegerField()),
                ('restaurant_offer_amount', models.IntegerField()),
                ('invoice_create_datetime', models.DateTimeField(verbose_name=b'invoice create')),
                ('invoice_create_by', models.CharField(max_length=45)),
                ('invoice_update_date', models.DateTimeField(verbose_name=b'invoice update')),
                ('invoice_update_by', models.CharField(max_length=45)),
                ('invoice_status', models.CharField(max_length=1)),
                ('consumer_id', models.ForeignKey(to='dealmonkapp.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='Offer_map',
            fields=[
                ('offer_map_id', models.AutoField(serialize=False, primary_key=True)),
                ('offer_map_time_from', models.TimeField(default=None, null=True, blank=True)),
                ('offer_map_time_to', models.TimeField(default=None, null=True, blank=True)),
                ('offer_map_date', models.DateField(default=None, null=True, blank=True)),
                ('offer_map_creation_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('offer_map_created_by', models.CharField(default=None, max_length=45, blank=True)),
                ('offer_map_update_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('offer_map_update_by', models.CharField(default=None, max_length=45, blank=True)),
                ('offer_map_status', models.CharField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('restaurant_name', models.CharField(max_length=45)),
                ('restaurant_owner_firstname', models.CharField(max_length=45, null=True, blank=True)),
                ('restaurant_owner_lastname', models.CharField(max_length=45, null=True, blank=True)),
                ('restaurant_owner_contact', models.CharField(max_length=45, null=True, blank=True)),
                ('restaurant_owner_email', models.CharField(max_length=45, null=True, blank=True)),
                ('restaurant_image', models.ImageField(default=b'default_icon_restaurant.png', upload_to=b'restaurant/')),
                ('restaurant_contactno', models.CharField(max_length=45)),
                ('restaurant_addr1', models.CharField(max_length=45)),
                ('restaurant_addr2', models.CharField(max_length=45)),
                ('restaurant_area', models.CharField(max_length=45)),
                ('restaurant_city', models.CharField(max_length=45)),
                ('restaurant_state', models.CharField(max_length=45)),
                ('restaurant_zipcode', models.CharField(max_length=45)),
                ('restaurant_description', models.CharField(max_length=45)),
                ('restaurant_opentime_day', models.TimeField(null=True, blank=True)),
                ('restaurant_closetime_day', models.TimeField(null=True, blank=True)),
                ('restaurant_opentime_eve', models.TimeField(null=True, blank=True)),
                ('restaurant_closetime_eve', models.TimeField(null=True, blank=True)),
                ('restaurant_status', models.CharField(default=1, max_length=1)),
                ('restaurant_has_branch', models.IntegerField(default=0, blank=True)),
                ('restaurant_lat', models.CharField(default=None, max_length=45, null=True, blank=True)),
                ('restaurant_lon', models.CharField(default=None, max_length=45, null=True, blank=True)),
                ('restaurant_create_date', models.DateField(null=True, blank=True)),
                ('restaurant_create_by', models.CharField(max_length=45)),
                ('restaurant_update_date', models.DateField(default=datetime.datetime.now, null=True, blank=True)),
                ('restaurant_update_by', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(parent_link=True, auto_created=True, to=settings.AUTH_USER_MODEL)),
                ('restaurant_admin_id', models.AutoField(serialize=False, editable=False, primary_key=True)),
                ('restaurant_admin_first_name', models.CharField(default=None, max_length=45)),
                ('restaurant_admin_last_name', models.CharField(default=None, max_length=45)),
                ('restaurant_admin_email', models.CharField(default=None, max_length=45)),
                ('restaurant_admin_contactno', models.CharField(default=None, max_length=45)),
                ('is_restaurant_admin_email_alert_on', models.CharField(default=1, max_length=1)),
                ('is_restaurant_admin_sms_alert_on', models.CharField(default=1, max_length=1)),
                ('restaurant_admin_status', models.CharField(default=1, max_length=1)),
                ('restaurant_admin_has_restaurant', models.IntegerField(default=0)),
                ('restaurant_admin_profile_pic', models.ImageField(default=None, upload_to=b'Admin_images/', max_length=500, verbose_name=b'Image')),
                ('restaurant_admin_create_date', models.DateTimeField(default=datetime.datetime.now, editable=False, blank=True)),
                ('restaurant_admin_create_by', models.CharField(default=None, max_length=45, null=True, blank=True)),
                ('restaurant_admin_update_date', models.DateTimeField(default=datetime.datetime.now, blank=True)),
                ('restaurant_admin_update_by', models.CharField(default=None, max_length=45, null=True, blank=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantBooking',
            fields=[
                ('restaurant_booking_id', models.AutoField(serialize=False, primary_key=True)),
                ('restaurant_booking_date', models.DateField(default=None, blank=True)),
                ('restaurant_booking_time_to', models.TimeField(default=None, blank=True)),
                ('restaurant_booking_time_from', models.TimeField(default=None, blank=True)),
                ('consumer_coupon_code', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_booking_covers', models.IntegerField(default=None, blank=True)),
                ('restaurant_booking_create_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('restaurant_booking_create_by', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_booking_update_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('restaurant_booking_update_by', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_booking_status', models.CharField(default=None, max_length=45, choices=[(b'Requested', b'Requested'), (b'Waiting', b'Waiting'), (b'Confirmed', b'Confirmed'), (b'Completed', b'Completed'), (b'No Show', b'No Show')])),
                ('restaurant_checkin_status', models.IntegerField(default=None, blank=True)),
                ('consumer_id', models.ForeignKey(default=None, blank=True, to='dealmonkapp.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('restaurant_branch_id', models.AutoField(default=None, serialize=False, primary_key=True)),
                ('restaurant_branch_name', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_contact', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_address1', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_address2', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_area', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_city', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_state', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_pincode', models.CharField(default=None, max_length=6, blank=True)),
                ('restaurant_branch_lat', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_lon', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_opentime_day', models.TimeField(default=None, null=True, blank=True)),
                ('restaurant_branch_closetime_day', models.TimeField(default=None, null=True, blank=True)),
                ('restaurant_branch_opentime_eve', models.TimeField(default=None, null=True, blank=True)),
                ('restaurant_branch_closetime_eve', models.TimeField(default=None, null=True, blank=True)),
                ('restaurant_branch_create_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('restaurant_branch_create_by', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_update_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('restaurant_branch_update_by', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_branch_status', models.CharField(default=1, max_length=1)),
                ('restaurant_admin_id', models.ForeignKey(default=None, to='dealmonkapp.RestaurantAdmin')),
                ('restaurant_id', models.ForeignKey(to='dealmonkapp.Restaurant', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOffer',
            fields=[
                ('restaurant_offer_id', models.AutoField(serialize=False, primary_key=True)),
                ('restaurant_offer_detail', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_offer_creation_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('restaurant_offer_created_by', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_offer_update_date', models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)),
                ('restaurant_offer_update_by', models.CharField(default=None, max_length=45, blank=True)),
                ('restaurant_offer_status', models.CharField(default=1, max_length=1)),
                ('restaurant_id', models.ForeignKey(default=None, blank=True, to='dealmonkapp.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('restaurant_rating_id', models.AutoField(serialize=False, primary_key=True)),
                ('restaurant_rating', models.IntegerField()),
                ('restaurant_feedback', models.CharField(max_length=45)),
                ('restaurant_issues', models.CharField(max_length=45)),
                ('restaurant_rating_create_by', models.CharField(max_length=45)),
                ('restaurant_rating_create_date', models.DateTimeField(verbose_name=b'rating create')),
                ('restaurant_update_by', models.CharField(max_length=45)),
                ('restaurant_update_date', models.DateTimeField(max_length=45)),
                ('consumer_id', models.ForeignKey(to='dealmonkapp.Consumer')),
                ('restaurant_branch_id', models.ForeignKey(default=None, blank=True, to='dealmonkapp.RestaurantBranch')),
                ('restaurant_id', models.ForeignKey(default=None, blank=True, to='dealmonkapp.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurantbooking',
            name='restaurant_branch_id',
            field=models.ForeignKey(default=None, blank=True, to='dealmonkapp.RestaurantBranch', null=True),
        ),
        migrations.AddField(
            model_name='restaurantbooking',
            name='restaurant_id',
            field=models.ForeignKey(default=None, blank=True, to='dealmonkapp.Restaurant', null=True),
        ),
        migrations.AddField(
            model_name='restaurantbooking',
            name='restaurant_offerMap_id',
            field=models.ForeignKey(default=None, blank=True, to='dealmonkapp.Offer_map'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_admin_id',
            field=models.ForeignKey(to='dealmonkapp.RestaurantAdmin', blank=True),
        ),
        migrations.AddField(
            model_name='offer_map',
            name='restaurant_id',
            field=models.ForeignKey(default=None, blank=True, to='dealmonkapp.Restaurant', null=True),
        ),
        migrations.AddField(
            model_name='offer_map',
            name='restaurant_offer_id',
            field=models.ForeignKey(to='dealmonkapp.RestaurantOffer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='restaurant_booking_id',
            field=models.ForeignKey(to='dealmonkapp.RestaurantBooking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='restaurant_id',
            field=models.ForeignKey(to='dealmonkapp.Restaurant'),
        ),
        migrations.AddField(
            model_name='cuisinerestaurentmap',
            name='restaurant_id',
            field=models.ForeignKey(default=None, blank=True, to='dealmonkapp.Restaurant', null=True),
        ),
        migrations.AddField(
            model_name='cuisinerestaurentbranchmap',
            name='restaurant_branch_id',
            field=models.ForeignKey(default=None, blank=True, to='dealmonkapp.RestaurantBranch', null=True),
        ),
    ]
